using CaseppCompiler.LexicalAnalyser;
using CaseppCompiler.LexicalAnalyser.Tokens;
using CaseppCompiler.SyntaxAnalyser;
using CaseppCompiler.SyntaxAnalyser.IntermediateLanguage;

using System.Collections.Concurrent;

namespace CaseppCompilerTest
{
    [TestFixture("grammar")]
    public class IntermediateLanguageTests(string type)
    {
        private ISyntaxAnalyser syntaxAnalyser;
        private ILexicalAnalyser lexicalAnalyser;
        private static readonly object[] tests =
        [
            new object[] { @"Program\EmptyProgram.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Functions\EmptyFunction.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p_f", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Functions\NestedFunctions.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p_f_g_h", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f_g_h", null, null),
                ("begin_block", "p_f_g", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f_g", null, null),
                ("begin_block", "p_f", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Assignment\SimpleAssignment.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Input\SimpleInput.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("inp", "x", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Print\SimplePrint.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("out", "0", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Return\SimpleReturn.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("retv", "0", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Expressions\SimpleExpression.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("+", "0", "9", "_T0"),
                (":=", "_T0", null, "x"),
                ("-", "0", "9", "_T1"),
                (":=", "_T1", null, "x"),
                (":=", "9", null, "x"),
                ("+", "5", "4", "_T2"),
                (":=", "_T2", null, "x"),
                ("-", "11", "2", "_T3"),
                (":=", "_T3", null, "x"),
                ("+", "5", "7", "_T4"),
                ("-", "_T4", "3", "_T5"),
                (":=", "_T5", null, "x"),
                ("*", "2", "2", "_T6"),
                ("+", "5", "_T6", "_T7"),
                (":=", "_T7", null, "x"),
                ("/", "8", "2", "_T8"),
                ("+", "5", "_T8", "_T9"),
                (":=", "_T9", null, "x"),
                ("/", "3", "2", "_T10"),
                ("*", "_T10", "9", "_T11"),
                (":=", "_T11", null, "x"),
                ("+", "2", "1", "_T12"),
                ("*", "3", "_T12", "_T13"),
                (":=", "_T13", null, "x"),
                ("*", "3", "i", "_T14"),
                ("*", "3", "i", "_T15"),
                ("-", "0", "_T15", "_T16"),
                ("*", "_T14", "_T16", "_T17"),
                (":=", "_T17", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Functions/FunctionCall.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p_f", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
                ("begin_block", "p_gi", null, null),
                ("retv", "v", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_gi", null, null),
                ("begin_block", "p_go", null, null),
                ("par", "_T0", "ret", null),
                ("call", "f", null, null),
                (":=", "_T0", null, "v"),
                ("retv", "0", null, null),
                ("end_block", "p_go", null, null),
                ("begin_block", "p_gio", null, null),
                ("par", "v", "cv", null),
                ("par", "_T1", "ret", null),
                ("call", "gi", null, null),
                (":=", "_T1", null, "v"),
                ("retv", "0", null, null),
                ("end_block", "p_gio", null, null),
                ("begin_block", "p_h", null, null),
                ("+", "v1", "v2", "_T2"),
                (":=", "_T2", null, "v3"),
                ("retv", "0", null, null),
                ("end_block", "p_h", null, null),
                ("begin_block", "p", null, null),
                ("par", "_T3", "ret", null),
                ("call", "f", null, null),
                (":=", "_T3", null, "x"),
                ("par", "a", "cv", null),
                ("par", "_T4", "ret", null),
                ("call", "gi", null, null),
                (":=", "_T4", null, "x"),
                ("par", "a", "cv", null),
                ("par", "_T5", "ret", null),
                ("call", "gi", null, null),
                (":=", "_T5", null, "x"),
                ("par", "a", "ret", null),
                ("par", "_T6", "ret", null),
                ("call", "go", null, null),
                (":=", "_T6", null, "x"),
                ("par", "a", "ref", null),
                ("par", "_T7", "ret", null),
                ("call", "gio", null, null),
                (":=", "_T7", null, "x"),
                ("par", "a", "cv", null),
                ("par", "b", "ref", null),
                ("par", "c", "ret", null),
                ("par", "_T8", "ret", null),
                ("call", "h", null, null),
                (":=", "_T8", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Functions/NestedFunctionCall.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("par", "_T0", "ret", null),
                ("call", "f", null, null),
                ("par", "_T0", "cv", null),
                ("par", "_T1", "ret", null),
                ("call", "g", null, null),
                (":=", "_T1", null, "x"),
                ("par", "a", "cv", null),
                ("par", "_T2", "ret", null),
                ("call", "g", null, null),
                ("par", "_T2", "cv", null),
                ("par", "_T3", "ret", null),
                ("call", "g", null, null),
                (":=", "_T3", null, "x"),
                ("par", "_T4", "ret", null),
                ("call", "f", null, null),
                ("par", "_T4", "cv", null),
                ("par", "a", "cv", null),
                ("par", "_T5", "ret", null),
                ("call", "h", null, null),
                (":=", "_T5", null, "x"),
                ("par", "a", "cv", null),
                ("par", "_T6", "ret", null),
                ("call", "g", null, null),
                ("par", "b", "cv", null),
                ("par", "_T7", "ret", null),
                ("call", "g", null, null),
                ("par", "_T6", "cv", null),
                ("par", "_T7", "cv", null),
                ("par", "_T8", "ret", null),
                ("call", "h", null, null),
                (":=", "_T8", null, "x"),
                ("par", "_T9", "ret", null),
                ("call", "f", null, null),
                ("par", "a", "cv", null),
                ("par", "_T9", "cv", null),
                ("par", "_T10", "ret", null),
                ("call", "h", null, null),
                ("par", "b", "cv", null),
                ("par", "_T11", "ret", null),
                ("call", "g", null, null),
                ("par", "_T10", "cv", null),
                ("par", "_T11", "cv", null),
                ("par", "c", "cv", null),
                ("par", "_T12", "ret", null),
                ("call", "F", null, null),
                (":=", "_T12", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Functions\LocalFunctionCall.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p_f_g", null, null),
                ("retv", "9", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f_g", null, null),
                ("begin_block", "p_f", null, null),
                ("par", "_T0", "ret", null),
                ("call", "g", null, null),
                (":=", "_T0", null, "x"),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Conditions\Condition.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "2"),
                (":=", "9", null, "x"),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("jump", null, null, "7"),
                ("jump", null, null, "8"),
                (":=", "9", null, "x"),
                ("jump", null, null, "12"),
                ("=", "x", "9", "12"),
                ("jump", null, null, "11"),
                ("jump", null, null, "13"),
                (":=", "9", null, "x"),
                ("jump", null, null, "16"),
                ("jump", null, null, "15"),
                ("jump", null, null, "16"),
                (":=", "9", null, "x"),
                ("jump", null, null, "21"),
                ("jump", null, null, "19"),
                ("=", "x", "9", "21"),
                ("jump", null, null, "22"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "24"),
                ("jump", null, null, "27"),
                ("jump", null, null, "25"),
                ("jump", null, null, "27"),
                (":=", "9", null, "x"),
                ("jump", null, null, "28"),
                ("jump", null, null, "29"),
                ("=", "x", "9", "31"),
                ("jump", null, null, "32"),
                (":=", "9", null, "x"),
                ("jump", null, null, "33"),
                ("=", "x", "9", "35"),
                ("jump", null, null, "39"),
                ("jump", null, null, "39"),
                ("=", "x", "9", "38"),
                ("jump", null, null, "39"),
                (":=", "9", null, "x"),
                ("<", "x", "9", "41"),
                ("jump", null, null, "44"),
                (">", "x", "9", "43"),
                ("jump", null, null, "44"),
                (":=", "9", null, "x"),
                ("<>", "x", "9", "49"),
                ("jump", null, null, "46"),
                ("<>", "x", "9", "49"),
                ("jump", null, null, "48"),
                ("jump", null, null, "49"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\If\EmptyIfNoElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("=", "x", "9", "3"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\If\EmptyIfEmptyElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("=", "x", "9", "3"),
                ("jump", null, null, "4"),
                ("jump", null, null, "4"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\If\BlockIfNoElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("=", "x", "9", "3"),
                ("jump", null, null, "4"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "6"),
                ("jump", null, null, "6"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\If\BlockIfBlockElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("=", "x", "9", "3"),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("jump", null, null, "6"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "8"),
                ("jump", null, null, "9"),
                ("jump", null, null, "9"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\While\EmptyWhileNoElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "7"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "5"),
                ("jump", null, null, "6"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\While\EmptyWhileEmptyElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "7"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "5"),
                ("jump", null, null, "6"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\While\BlockWhileNoElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "13"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "5"),
                ("jump", null, null, "9"),
                (":=", "9", null, "x"),
                ("jump", null, null, "9"),
                (":=", "9", null, "x"),
                ("jump", null, null, "3"),
                ("=", "x", "9", "11"),
                ("jump", null, null, "12"),
                ("jump", null, null, "9"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\While\BlockWhileBlockElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "18"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "5"),
                ("jump", null, null, "9"),
                (":=", "9", null, "x"),
                ("jump", null, null, "10"),
                (":=", "9", null, "x"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "12"),
                ("jump", null, null, "14"),
                ("jump", null, null, "14"),
                ("jump", null, null, "10"),
                ("=", "x", "9", "16"),
                ("jump", null, null, "17"),
                ("jump", null, null, "14"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Switchcase\NoCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Switchcase\ManyCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (">", "x", "9", "3"),
                ("jump", null, null, "4"),
                ("jump", null, null, "12"),
                ("=", "x", "9", "6"),
                ("jump", null, null, "8"),
                (":=", "work", null, "setup"),
                ("jump", null, null, "12"),
                ("<", "x", "9", "10"),
                ("jump", null, null, "11"),
                ("jump", null, null, "12"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Incase\NoCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "4"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Incase\ManyCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "12"),
                (":=", "9", null, "x"),
                (">", "x", "9", "5"),
                ("jump", null, null, "6"),
                ("jump", null, null, "11"),
                ("=", "x", "9", "8"),
                ("jump", null, null, "9"),
                (":=", "work", null, "setup"),
                ("<", "x", "9", "11"),
                ("jump", null, null, "11"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Untilcase\NoCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "6"),
                (":=", "9", null, "x"),
                ("=", "i", "1", "5"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Untilcase\ManyCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "14"),
                (":=", "9", null, "x"),
                (">", "x", "9", "5"),
                ("jump", null, null, "5"),
                ("=", "x", "9", "7"),
                ("jump", null, null, "8"),
                (":=", "work", null, "setup"),
                ("<", "x", "9", "10"),
                ("jump", null, null, "11"),
                ("jump", null, null, "13"),
                ("=", "i", "1", "13"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Whilecase\NoCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Whilecase\ManyCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "16"),
                (":=", "9", null, "x"),
                (">", "x", "9", "5"),
                ("jump", null, null, "6"),
                ("jump", null, null, "3"),
                ("=", "x", "9", "8"),
                ("jump", null, null, "10"),
                (":=", "work", null, "setup"),
                ("jump", null, null, "3"),
                ("<", "x", "9", "12"),
                ("jump", null, null, "14"),
                ("jump", null, null, "15"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Break\BreakProgram.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Break\BreakFunction.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p_f", null, null),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Break\BreakBlock.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "11"),
                (":=", "9", null, "x"),
                ("jump", null, null, "9"),
                (":=", "9", null, "x"),
                ("jump", null, null, "10"),
                (":=", "9", null, "x"),
                ("jump", null, null, "11"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Forcase\NoCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "9"),
                (":=", "9", null, "x"),
                (":=", "0", null, "i"),
                ("<", "i", "0", "6"),
                ("jump", null, null, "8"),
                ("+", "i", "1", "i"),
                ("jump", null, null, "4"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Forcase\ManyCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "17"),
                (":=", "9", null, "x"),
                (":=", "0", null, "i"),
                ("<", "i", "1", "6"),
                ("jump", null, null, "16"),
                ("+", "i", "1", "i"),
                (">", "x", "9", "9"),
                ("jump", null, null, "10"),
                ("jump", null, null, "15"),
                ("=", "x", "9", "12"),
                ("jump", null, null, "13"),
                ("jump", null, null, "16"),
                ("<", "x", "9", "15"),
                ("jump", null, null, "15"),
                ("jump", null, null, "4"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
        ];

        [SetUp]
        public void Setup()
        {
            lexicalAnalyser = LexicalAnalyserFactory.Create();
            syntaxAnalyser = SyntaxAnalyserFactory.Create(type);
        }

        [TestCaseSource(nameof(tests))]
        public void Test(string file, (string?, string?, string?, string?)[] expectedQuads)
        {
            string path = Path.Combine(TestContext.CurrentContext.TestDirectory, $@"IntermediateLanguageTests\{file}");
            using BlockingCollection<Token> tokenQueue = [];
            using IntermediateProgram program = new();

            lexicalAnalyser.Analyse(File.OpenRead(path), tokenQueue);
            syntaxAnalyser.Analyse(tokenQueue, program);

            var ep = program.ToQuads().GetEnumerator();
            var ee = expectedQuads.GetEnumerator();
            while (true)
                switch ((ep.MoveNext(), ee.MoveNext()))
                {
                    case (true, true):
                        Assert.That(ep.Current, Is.EqualTo(ee.Current));
                        continue;
                    case (false, false):
                        return;
                    default:
                        Assert.Fail("Length mismatch");
                        return;
                }
        }
    }
}
