using CaseppCompiler;
using CaseppCompiler.CodeGenerator;
using CaseppCompiler.LexicalAnalyser;
using CaseppCompiler.LexicalAnalyser.Tokens;
using CaseppCompiler.SyntaxAnalyser;
using CaseppCompiler.SyntaxAnalyser.IntermediateLanguage;

using NUnit.Framework.Constraints;

namespace CaseppCompilerTest
{
    [TestFixture("grammar")]
    public class IntermediateLanguageTests(string type)
    {
        private ISyntaxAnalyser syntaxAnalyser;
        private ILexicalAnalyser lexicalAnalyser;

        private static readonly object[] happyTests =
        [
            new object[] { @"Program\EmptyProgram.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Functions\EmptyFunction.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
                ("begin_block", "p_f", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
            } },
            new object[] { @"Functions\NestedFunctions.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
                ("begin_block", "p_f", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
                ("begin_block", "p_f_g", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f_g", null, null),
                ("begin_block", "p_f_g_h", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f_g_h", null, null),
            } },
            new object[] { @"Statements\Assignment\SimpleAssignment.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Input\SimpleInput.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("in", "x", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Print\SimplePrint.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("+", "5", "4", "_T0"),
                ("out", "_T0", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Return\SimpleReturn.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("+", "5", "4", "_T0"),
                ("retv", "_T0", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Expressions\SimpleExpression.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "0", null, "i"),
                ("+", "0", "9", "_T0"),
                (":=", "_T0", null, "x"),
                ("-", "0", "9", "_T1"),
                (":=", "_T1", null, "x"),
                (":=", "9", null, "x"),
                ("+", "5", "4", "_T2"),
                (":=", "_T2", null, "x"),
                ("-", "11", "2", "_T3"),
                (":=", "_T3", null, "x"),
                ("+", "5", "7", "_T4"),
                ("-", "_T4", "3", "_T5"),
                (":=", "_T5", null, "x"),
                ("*", "2", "2", "_T6"),
                ("+", "5", "_T6", "_T7"),
                (":=", "_T7", null, "x"),
                ("/", "8", "2", "_T8"),
                ("+", "5", "_T8", "_T9"),
                (":=", "_T9", null, "x"),
                ("/", "3", "2", "_T10"),
                ("*", "_T10", "9", "_T11"),
                (":=", "_T11", null, "x"),
                ("+", "2", "1", "_T12"),
                ("*", "3", "_T12", "_T13"),
                (":=", "_T13", null, "x"),
                ("*", "3", "i", "_T14"),
                ("*", "3", "i", "_T15"),
                ("-", "0", "_T15", "_T16"),
                ("*", "_T14", "_T16", "_T17"),
                (":=", "_T17", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Functions\FunctionCall.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "1", null, "a"),
                (":=", "2", null, "b"),
                ("par", "_T3", "ret", null),
                ("call", "f", null, null),
                (":=", "_T3", null, "x"),
                ("par", "a", "cv", null),
                ("par", "_T4", "ret", null),
                ("call", "gi", null, null),
                (":=", "_T4", null, "x"),
                ("par", "a", "cv", null),
                ("par", "_T5", "ret", null),
                ("call", "gi", null, null),
                (":=", "_T5", null, "x"),
                ("par", "a", "ret", null),
                ("par", "_T6", "ret", null),
                ("call", "go", null, null),
                (":=", "_T6", null, "x"),
                ("par", "a", "ref", null),
                ("par", "_T7", "ret", null),
                ("call", "gio", null, null),
                (":=", "_T7", null, "x"),
                ("par", "a", "cv", null),
                ("par", "b", "ref", null),
                ("par", "c", "ret", null),
                ("par", "_T8", "ret", null),
                ("call", "h", null, null),
                (":=", "_T8", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
                ("begin_block", "p_f", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
                ("begin_block", "p_gi", null, null),
                ("retv", "v", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_gi", null, null),
                ("begin_block", "p_go", null, null),
                ("par", "_T0", "ret", null),
                ("call", "f", null, null),
                (":=", "_T0", null, "v"),
                ("retv", "0", null, null),
                ("end_block", "p_go", null, null),
                ("begin_block", "p_gio", null, null),
                ("par", "v", "cv", null),
                ("par", "_T1", "ret", null),
                ("call", "gi", null, null),
                (":=", "_T1", null, "v"),
                ("retv", "0", null, null),
                ("end_block", "p_gio", null, null),
                ("begin_block", "p_h", null, null),
                ("+", "v1", "v2", "_T2"),
                (":=", "_T2", null, "v3"),
                ("retv", "0", null, null),
                ("end_block", "p_h", null, null),
            } },
            new object[] { @"Functions\NestedFunctionCall.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("par", "_T0", "ret", null),
                ("call", "f", null, null),
                ("par", "_T0", "cv", null),
                ("par", "_T1", "ret", null),
                ("call", "g", null, null),
                (":=", "_T1", null, "a"),
                ("par", "a", "cv", null),
                ("par", "_T2", "ret", null),
                ("call", "g", null, null),
                ("par", "_T2", "cv", null),
                ("par", "_T3", "ret", null),
                ("call", "g", null, null),
                (":=", "_T3", null, "b"),
                ("par", "_T4", "ret", null),
                ("call", "f", null, null),
                ("par", "_T4", "cv", null),
                ("par", "a", "cv", null),
                ("par", "_T5", "ret", null),
                ("call", "h", null, null),
                (":=", "_T5", null, "c"),
                ("par", "a", "cv", null),
                ("par", "_T6", "ret", null),
                ("call", "g", null, null),
                ("par", "b", "cv", null),
                ("par", "_T7", "ret", null),
                ("call", "g", null, null),
                ("par", "_T6", "cv", null),
                ("par", "_T7", "cv", null),
                ("par", "_T8", "ret", null),
                ("call", "h", null, null),
                (":=", "_T8", null, "x"),
                ("par", "_T9", "ret", null),
                ("call", "f", null, null),
                ("par", "a", "cv", null),
                ("par", "_T9", "cv", null),
                ("par", "_T10", "ret", null),
                ("call", "h", null, null),
                ("par", "b", "cv", null),
                ("par", "_T11", "ret", null),
                ("call", "g", null, null),
                ("par", "_T10", "cv", null),
                ("par", "_T11", "cv", null),
                ("par", "c", "cv", null),
                ("par", "_T12", "ret", null),
                ("call", "F", null, null),
                (":=", "_T12", null, "y"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
                ("begin_block", "p_f", null, null),
                ("retv", "1", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
                ("begin_block", "p_g", null, null),
                ("retv", "2", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_g", null, null),
                ("begin_block", "p_h", null, null),
                ("retv", "3", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_h", null, null),
                ("begin_block", "p_F", null, null),
                ("retv", "4", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_F", null, null),
            } },
            new object[] { @"Functions\LocalFunctionCall.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
                ("begin_block", "p_f", null, null),
                ("par", "_T0", "ret", null),
                ("call", "g", null, null),
                (":=", "_T0", null, "x"),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
                ("begin_block", "p_f_g", null, null),
                ("retv", "9", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f_g", null, null),
            } },
            new object[] { @"Conditions\SimpleCondition.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "2"),
                (":=", "9", null, "x"),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "7"),
                ("jump", null, null, "8"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Conditions\CompositeCondition.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("<", "x", "9", "6"),
                ("jump", null, null, "4"),
                (">", "x", "9", "6"),
                ("jump", null, null, "7"),
                (":=", "9", null, "x"),
                ("<=", "x", "9", "9"),
                ("jump", null, null, "12"),
                (">=", "x", "9", "11"),
                ("jump", null, null, "12"),
                (":=", "9", null, "x"),
                ("jump", null, null, "13"),
                ("jump", null, null, "14"),
                ("=", "x", "9", "16"),
                ("jump", null, null, "17"),
                (":=", "9", null, "x"),
                ("jump", null, null, "18"),
                ("jump", null, null, "19"),
                ("=", "x", "9", "21"),
                ("jump", null, null, "22"),
                (":=", "9", null, "x"),
                ("jump", null, null, "23"),
                ("jump", null, null, "24"),
                ("=", "x", "9", "26"),
                ("jump", null, null, "27"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Conditions\InvertedCondition.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("<>", "x", "9", "5"),
                ("jump", null, null, "4"),
                (":=", "9", null, "x"),
                ("<", "x", "9", "7"),
                ("jump", null, null, "9"),
                (">", "x", "9", "10"),
                ("jump", null, null, "9"),
                (":=", "9", null, "x"),
                ("<=", "x", "9", "15"),
                ("jump", null, null, "12"),
                (">=", "x", "9", "15"),
                ("jump", null, null, "14"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "17"),
                ("jump", null, null, "18"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\If\EmptyIfNoElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("=", "x", "9", "4"),
                ("jump", null, null, "4"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\If\EmptyIfEmptyElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("=", "x", "9", "4"),
                ("jump", null, null, "5"),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\If\BlockIfNoElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("=", "x", "9", "4"),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "7"),
                ("jump", null, null, "7"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\If\BlockIfBlockElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("=", "x", "9", "4"),
                ("jump", null, null, "6"),
                (":=", "9", null, "x"),
                ("jump", null, null, "7"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "9"),
                ("jump", null, null, "10"),
                ("jump", null, null, "10"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\While\EmptyWhileNoElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "8"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "5"),
                ("jump", null, null, "6"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\While\EmptyWhileEmptyElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "8"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "5"),
                ("jump", null, null, "6"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\While\BlockWhileNoElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "16"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "5"),
                ("jump", null, null, "7"),
                ("jump", null, null, "7"),
                ("jump", null, null, "3"),
                ("=", "x", "9", "9"),
                ("jump", null, null, "11"),
                ("jump", null, null, "7"),
                ("jump", null, null, "7"),
                ("=", "x", "9", "13"),
                ("jump", null, null, "14"),
                ("jump", null, null, "11"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\While\BlockWhileBlockElse.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "25"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "5"),
                ("jump", null, null, "8"),
                ("jump", null, null, "10"),
                ("jump", null, null, "3"),
                ("jump", null, null, "3"),
                ("jump", null, null, "10"),
                ("jump", null, null, "3"),
                ("=", "x", "9", "12"),
                ("jump", null, null, "15"),
                ("jump", null, null, "15"),
                ("jump", null, null, "10"),
                ("jump", null, null, "10"),
                ("=", "x", "9", "17"),
                ("jump", null, null, "18"),
                ("jump", null, null, "15"),
                ("jump", null, null, "20"),
                ("jump", null, null, "15"),
                ("=", "x", "9", "22"),
                ("jump", null, null, "23"),
                ("jump", null, null, "20"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Switchcase\NoCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Switchcase\ManyCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                (">", "x", "9", "4"),
                ("jump", null, null, "5"),
                ("jump", null, null, "13"),
                ("=", "x", "9", "7"),
                ("jump", null, null, "9"),
                (":=", "42", null, "x"),
                ("jump", null, null, "13"),
                ("<", "x", "9", "11"),
                ("jump", null, null, "12"),
                ("jump", null, null, "13"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Untilcase\NoCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "8"),
                (":=", "9", null, "x"),
                ("-", "x", "9", "_T0"),
                ("=", "0", "_T0", "6"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Untilcase\ManyCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "14"),
                (":=", "9", null, "x"),
                (">", "x", "9", "5"),
                ("jump", null, null, "6"),
                ("jump", null, null, "12"),
                ("<", "x", "9", "8"),
                ("jump", null, null, "9"),
                ("jump", null, null, "3"),
                ("-", "x", "9", "_T0"),
                ("=", "0", "_T0", "12"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Whilecase\NoCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "6"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Whilecase\ManyCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "14"),
                (":=", "9", null, "x"),
                (">", "x", "9", "5"),
                ("jump", null, null, "7"),
                ("jump", null, null, "12"),
                ("jump", null, null, "3"),
                ("<", "x", "9", "9"),
                ("jump", null, null, "11"),
                ("jump", null, null, "3"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Incase\NoCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "7"),
                (":=", "9", null, "x"),
                (":=", "0", null, "_T0"),
                ("<>", "_T0", "0", "3"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Incase\ManyCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "15"),
                (":=", "9", null, "x"),
                (":=", "0", null, "_T0"),
                (">", "x", "9", "6"),
                ("jump", null, null, "8"),
                ("jump", null, null, "13"),
                (":=", "1", null, "_T0"),
                ("<", "x", "9", "10"),
                ("jump", null, null, "12"),
                ("jump", null, null, "3"),
                (":=", "1", null, "_T0"),
                ("<>", "_T0", "0", "3"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Forcase\NoCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "11"),
                (":=", "9", null, "x"),
                (":=", "0", null, "i"),
                ("-", "x", "9", "_T0"),
                ("<", "i", "_T0", "7"),
                ("jump", null, null, "9"),
                ("+", "i", "1", "i"),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Forcase\ManyCases.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "23"),
                (":=", "9", null, "x"),
                (":=", "0", null, "i"),
                ("+", "x", "9", "_T0"),
                ("<", "i", "_T0", "7"),
                ("jump", null, null, "21"),
                ("+", "i", "1", "i"),
                (">", "x", "9", "10"),
                ("jump", null, null, "11"),
                ("jump", null, null, "20"),
                ("=", "x", "9", "13"),
                ("jump", null, null, "14"),
                ("jump", null, null, "21"),
                ("<>", "x", "9", "16"),
                ("jump", null, null, "17"),
                ("jump", null, null, "3"),
                ("<", "x", "9", "19"),
                ("jump", null, null, "20"),
                ("jump", null, null, "8"),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Break\BreakProgram.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("jump", null, null, "5"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Break\BreakFunction.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
                ("begin_block", "p_f", null, null),
                ("jump", null, null, "8"),
                (":=", "9", null, "x"),
                ("jump", null, null, "8"),
                (":=", "9", null, "x"),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
            } },
            new object[] { @"Statements\Break\BreakBlock.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "11"),
                (":=", "9", null, "x"),
                ("jump", null, null, "9"),
                (":=", "9", null, "x"),
                ("jump", null, null, "10"),
                (":=", "9", null, "x"),
                ("jump", null, null, "11"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Break\BreakZero.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Repeat\RepeatProgram.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Repeat\RepeatFunction.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
                ("begin_block", "p_f", null, null),
                (":=", "9", null, "x"),
                ("jump", null, null, "4"),
                (":=", "9", null, "x"),
                ("jump", null, null, "4"),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
            } },
            new object[] { @"Statements\Repeat\RepeatBlock.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                (":=", "9", null, "x"),
                ("jump", null, null, "2"),
                (":=", "9", null, "x"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("jump", null, null, "1"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Statements\Repeat\RepeatZero.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"ILInstructions\Assignment\Assignment.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (":=", "9", null, "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"ILInstructions\Input\Input.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("in", "x", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"ILInstructions\Output\Output.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("out", "9", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"ILInstructions\Halt\Halt.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("halt", null, null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"ILInstructions\Par\Par.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("par", "9", "cv", null),
                ("par", "x", "ref", null),
                ("par", "x", "ret", null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"ILInstructions\Call\Call.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("call", "f", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
                ("begin_block", "p_f", null, null),
                ("retv", "9", null, null),
                ("retv", "0", null, null),
                ("end_block", "p_f", null, null),
            } },
            new object[] { @"ILInstructions\Return\Return.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("retv", "9", null, null),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"ILInstructions\Operation\Operation.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("+", "5", "4", "x"),
                ("-", "11", "2", "x"),
                ("*", "3", "3", "x"),
                ("/", "19", "2", "x"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"ILInstructions\Jump\Jump.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                ("jump", null, null, "2"),
                (":=", "9", null, "x"),
                ("jump", null, null, "3"),
                (":=", "9", null, "x"),
                ("jump", null, null, "4"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"ILInstructions\Comparison\Comparison.c++", new (string?, string?, string?, string?)[] {
                ("begin_block", "p", null, null),
                (">", "x", "9", "2"),
                (":=", "9", null, "x"),
                ("=", "x", "9", "3"),
                (":=", "9", null, "x"),
                ("<", "x", "9", "4"),
                ("halt", null, null, null),
                ("end_block", "p", null, null),
            } },
            new object[] { @"Scope\Scope.c++", null! },
            new object[] { @"Initialisation\Initialisation.c++", null! },
            new object[] { @"Initialisation\InitialiseFromFunction.c++", null! },
        ];

        private static readonly object[] sadTests =
        [
            new object[] { @"ParameterAlreadyExists.c++", new IResolveConstraint[]
            {
                Is.EqualTo("Line 3, Column 16: Invalid Formal Parameter \"Out Parameter x\" for Function \"f\"."),
                Is.EqualTo("Invalid Symbol \"x\" for the current Scope."),
                Is.EqualTo("Symbol \"x\" already exists."),
            } },

            new object[] { @"ILInstructions\LabelAlreadyExists.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 9: Label \"l\" is already set.") } },

            new object[] { @"ILInstructions\Assignment\NoValue.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected Constant or Variable ID for 1st argument.") } },
            new object[] { @"ILInstructions\Assignment\NoNull.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected no 2nd argument.") } },
            new object[] { @"ILInstructions\Assignment\AssignToConstant.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected Variable ID for 3rd argument.") } },

            new object[] { @"ILInstructions\Input\InputToConstant.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected Variable ID for 1st argument.") } },
            new object[] { @"ILInstructions\Input\NoNull1.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected no 2nd argument.") } },
            new object[] { @"ILInstructions\Input\NoNull2.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected no 3rd argument.") } },

            new object[] { @"ILInstructions\Output\OutputNull.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected Constant or Variable ID for 1st argument.") } },
            new object[] { @"ILInstructions\Output\NoNull1.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected no 2nd argument.") } },
            new object[] { @"ILInstructions\Output\NoNull2.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected no 3rd argument.") } },

            new object[] { @"ILInstructions\Halt\NoNull1.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 4: Expected no 1st argument.") } },
            new object[] { @"ILInstructions\Halt\NoNull2.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 4: Expected no 2nd argument.") } },
            new object[] { @"ILInstructions\Halt\NoNull3.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 4: Expected no 3rd argument.") } },

            new object[] { @"ILInstructions\Par\NoValue.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 4: Expected Constant or Variable ID for 1st argument.") } },
            new object[] { @"ILInstructions\Par\NoType.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 4: Expected Parameter Type for 2nd argument.") } },
            new object[] { @"ILInstructions\Par\NoNull.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 4: Expected no 3rd argument.") } },

            new object[] { @"ILInstructions\Call\CallConstant.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected Function Name for 1st argument.") } },
            new object[] { @"ILInstructions\Call\NoNull1.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected no 2nd argument.") } },
            new object[] { @"ILInstructions\Call\NoNull2.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected no 3rd argument.") } },

            new object[] { @"ILInstructions\Return\NoNull1.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected no 2nd argument.") } },
            new object[] { @"ILInstructions\Return\NoNull2.c++", new IResolveConstraint[] { Is.EqualTo("Line 4, Column 4: Expected no 3rd argument.") } },

            new object[] { @"ILInstructions\Operation\NoOperand1.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 4: Expected Constant or Variable ID for 1st argument.") } },
            new object[] { @"ILInstructions\Operation\NoOperand2.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 4: Expected Constant or Variable ID for 2nd argument.") } },
            new object[] { @"ILInstructions\Operation\NoVariable.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 4: Expected Variable ID for 3rd argument.") } },

            new object[] { @"ILInstructions\Jump\NoNull1.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 7: Expected no 1st argument.") } },
            new object[] { @"ILInstructions\Jump\NoNull2.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 7: Expected no 2nd argument.") } },
            new object[] { @"ILInstructions\Jump\NotLabel.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 7: Expected Label Name for 3rd argument.") } },
            new object[] { @"ILInstructions\Jump\LabelNotSet.c++", new IResolveConstraint[]
            {
                Is.EqualTo("Line 4, Column 1: Cannot exit Scope in the current Function."),
                Is.EqualTo("Cannot exit the current Scope."),
                Is.EqualTo("Cannot exit Scope due to Symbol \"m\"."),
                Is.EqualTo("This Label has not been set."),
            } },

            new object[] { @"ILInstructions\Comparison\NoOperand1.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 7: Expected Constant or Variable ID for 1st argument.") } },
            new object[] { @"ILInstructions\Comparison\NoOperand2.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 7: Expected Constant or Variable ID for 2nd argument.") } },
            new object[] { @"ILInstructions\Comparison\NotLabel.c++", new IResolveConstraint[] { Is.EqualTo("Line 3, Column 7: Expected Label Name for 3rd argument.") } },

            new object[] { @"Initialisation\NoInitialisation.c++", new IResolveConstraint[]
            {
                Is.EqualTo("Line 4, Column 9: Cannot use variable x."),
                Is.EqualTo("Use of uninitialised variable x."),
            } },
            new object[] { @"Initialisation\InitialiseLocalInstead.c++", new IResolveConstraint[]
            {
                Is.EqualTo("Line 8, Column 9: Cannot use variable x."),
                Is.EqualTo("Use of uninitialised variable x."),
            } },
            new object[] { @"Initialisation\InitialiseFromFunctionNoCall.c++", new IResolveConstraint[]
            {
                Is.EqualTo("Line 7, Column 9: Cannot use variable x."),
                Is.EqualTo("Use of uninitialised variable x."),
            } },
            new object[] { @"Initialisation\InitialiseFromFunctionUseFirst.c++", new IResolveConstraint[]
            {
                Is.EqualTo("Line 7, Column 9: Cannot use function \"f\"."),
                Is.EqualTo("Use of uninitialised variables in function \"f\": \"x\"."),
            } },
            new object[] { @"Initialisation\InitialiseFromFunctionAlreadyUsed.c++", new IResolveConstraint[]
            {
                Is.EqualTo("Line 13, Column 9: Cannot use function \"g\"."),
                Is.EqualTo("Use of uninitialised variables in function \"g\": \"x\"."),
            } },
            new object[] { @"Initialisation\NoOutParameterAssignment.c++", new IResolveConstraint[] { Is.EqualTo("Line 6, Column 2: No assignment to Out Parameter \"x\".") } },
        ];

        [SetUp]
        public void Setup()
        {
            lexicalAnalyser = LexicalAnalyserFactory.Create();
            syntaxAnalyser = SyntaxAnalyserFactory.Create(type);
        }

        [TestCaseSource(nameof(happyTests))]
        public async Task HappyAsync(string file, (string?, string?, string?, string?)[]? expectedQuads)
        {
            string path = Path.Combine(TestContext.CurrentContext.TestDirectory, $@"IntermediateLanguageTests\Happy\{file}");

            Stream<Token> tokens = new();
            IntermediateProgram program = new();

            await lexicalAnalyser.Analyse(File.OpenRead(path), tokens);
            await syntaxAnalyser.Analyse(tokens, program);

            if (expectedQuads == null) return;

            var ep = program.ToQuadsConsuming().GetAsyncEnumerator();
            var ee = expectedQuads.GetEnumerator();
            while (true)
                switch ((await ep.MoveNextAsync(), ee.MoveNext()))
                {
                    case (true, true):
                        Assert.That(ep.Current, Is.EqualTo(ee.Current));
                        continue;
                    case (false, false):
                        return;
                    default:
                        Assert.Fail("Length mismatch");
                        return;
                }
        }

        [TestCaseSource(nameof(sadTests))]
        public void Sad(string file, IEnumerable<IResolveConstraint> messageConstraints)
        {
            string path = Path.Combine(TestContext.CurrentContext.TestDirectory, $@"IntermediateLanguageTests\Sad\{file}");

            Exception? e = Assert.ThrowsAsync<SyntaxAnalyserException>(async () =>
            {
                Stream<Token> tokens = new();
                IntermediateProgram program = new();

                await lexicalAnalyser.Analyse(File.OpenRead(path), tokens);
                await syntaxAnalyser.Analyse(tokens, program);
            },
            $"Expected SyntaxAnalyserException.");

            foreach (var messageConstraint in messageConstraints)
            {
                Assert.That(e, Is.Not.Null, $"Expected more Inner Exceptions.");
                Assert.That(e.Message, messageConstraint);
                e = e.InnerException;
            }
        }
    }
}
